### ISSUE TITLE
OTAA Setup?

### ISSUE THREAD

**Issue by proffalken** [itofficeeu/ito-rfid-rc522-lora#1]
Hi!

This looks great, however it appears to be using ABP only.

Is there a way to get it to use OTAA instead?

**Comment by itofficeeu** [comment]
Hi, I'm sorry. Not for now. The platform The Things Network also has changed their backend, so that the code would have to be rewritten for the new backend. - The code is at it is, proof of concept like, but time has eaten it up, for now.  But hey, this is open source: You could modify it to the new backend, and make it OTAA yourself.

**Comment by proffalken** [comment]
Yeah, that's fair enough, figured it was worth an ask, I'll see what I can do with it - it's a great place to start at least!
